Fix ArgumentError when Fallbacks#map used as in Hash
This can cause a problem with Airbrake when a Fallbacks instance is set
as a thread-local variable:

Thread.current[:foo] = I18n::Locale::Fallbacks.new(:"de-AT" => :de)
notice = Airbrake.build_notice("hi")
Airbrake::Filters::ThreadFilter.new.call(notice)

ArgumentError: wrong number of arguments (given 0, expected 1) from
gems/i18n-1.8.10/lib/i18n/locale/fallbacks.rb:74:in `map'